# welcome to numpy tutorial

In [1]:
import numpy as np

In [2]:
print("Hello Zelam")

Hello Zelam


In [12]:
myarr = np.array([2,6,55,85], np.int8)

In [13]:
myarr

array([ 2,  6, 55, 85], dtype=int8)

In [14]:
myarr[0,1]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [15]:
myarr = np.array([[2,6,55,85]], np.int8)

In [16]:
myarr

array([[ 2,  6, 55, 85]], dtype=int8)

In [17]:
myarr[0,1]

6

In [20]:
myarr[0]

array([ 2,  6, 55, 85], dtype=int8)

In [21]:
myarr[0,0]

2

In [18]:
myarr.shape

(1, 4)

In [19]:
myarr.dtype

dtype('int8')

**To change the element of list**

In [22]:
myarr[0,1] = 12

In [23]:
myarr

array([[ 2, 12, 55, 85]], dtype=int8)

In [24]:
myarr[0,1]

12

**Array creation methods:
1.Conversion from other Python structures(e.g.,lists, tuples)
2.Intrinsic numpy array creation objects(e.g., arange, ones, zeros, etc.)
3.Reading arrays from disk, either from standard or custom formats
4.Creation arrays from raw bytes through the use of strings or buffers
5.Use of special library functions(e.g., random)**

**Array creation: 1.Conversion from other Python structures**

In [31]:
listarray = np.array([[1,2,3], [5,8,6], [0,3,1]])

In [32]:
listarray

array([[1, 2, 3],
       [5, 8, 6],
       [0, 3, 1]])

In [33]:
listarray.dtype

dtype('int32')

In [34]:
listarray.shape

(3, 3)

In [35]:
listarray.size

9

In [36]:
np.array({34,25,65})

array({65, 25, 34}, dtype=object)

In [37]:
np.array({34,25,25})

array({25, 34}, dtype=object)

**2.Intrinsic numpy array creation objects**

In [38]:
zeros = np.zeros((3,5))

In [39]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [40]:
zeros.dtype

dtype('float64')

In [41]:
zeros.shape

(3, 5)

In [42]:
zeros.size

15

**arange() function create numpy array**

In [43]:
rng = np.arange(15)

In [44]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [47]:
lspace = np.linspace(1,50,15)

In [48]:
lspace

array([ 1. ,  4.5,  8. , 11.5, 15. , 18.5, 22. , 25.5, 29. , 32.5, 36. ,
       39.5, 43. , 46.5, 50. ])

**gives random element**

In [49]:
emp = np.empty((4,6))

In [51]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.33511290e-306, 6.23058368e-307, 2.22526399e-307],
       [6.23053614e-307, 7.56592338e-307, 1.60216183e-306,
        7.56602523e-307, 3.56043054e-307, 1.37961641e-306],
       [2.22518251e-306, 1.33511969e-306, 3.11525958e-307,
        1.69118108e-306, 8.06632139e-308, 1.20160711e-306],
       [1.69119330e-306, 1.29062229e-306, 1.24610383e-306,
        1.86918699e-306, 8.45602762e-307, 9.34603679e-307]])

In [52]:
emp_like = np.empty_like(lspace)

In [53]:
emp_like

array([ 1. ,  4.5,  8. , 11.5, 15. , 18.5, 22. , 25.5, 29. , 32.5, 36. ,
       39.5, 43. , 46.5, 50. ])

In [56]:
ide = np.identity(10)

In [57]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [58]:
ide.shape

(10, 10)

In [59]:
ide.size

100

In [77]:
arr = np.arange(99)

In [78]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [79]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [80]:
arr.reshape(3,31)

ValueError: cannot reshape array of size 99 into shape (3,31)

In [81]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [83]:
arr = arr.reshape(3,33)

In [84]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

**to make 1D array**

In [86]:
arr = arr.ravel()

In [87]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [88]:
arr.shape

(99,)

**1D=[1,2,3,4,5]= axis0
2D=[[1,2,3][4,5,6][7,1,0]]= 2[Axis0,Axis1]
all the Y-axis = axis0
all the X-axis = axis1**


In [89]:
x = [[1,2,3], [4,5,6], [7,1,0]]

In [90]:
ar = np.array(x)

In [91]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [92]:
ar.sum(axis=0)

array([12,  8,  9])

In [93]:
ar.sum(axis=1)

array([ 6, 15,  8])

**Transpose the original matrix**

In [95]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [96]:
ar.flat


In [97]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [98]:
ar.ndim

2

In [99]:
ar.size

9

In [100]:
ar.nbytes

36

In [101]:
arr.nbytes

396

**With parenthisis it is called function  &  without parenthisis it is called an Atrributes**

In [104]:
one = np.array([1,50,4,25,6])

In [105]:
one.argmax()

1

In [106]:
one.argmin()

0

**It returns array's element indexs in assending order**

In [108]:
one.argsort()

array([0, 2, 4, 3, 1], dtype=int64)

In [109]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [111]:
ar.argmin()

8

In [112]:
ar.argmax()

6

In [113]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [114]:
ar.argmin(axis=1)

array([0, 0, 2], dtype=int64)

In [115]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [116]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [117]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [124]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [125]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [126]:
ar2 = np.array([[1,2,1],
              [4,0,6],
              [8,1,0]])

In [127]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [128]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

**In list we cannot add or multiply two different lists**

In [131]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [132]:
ar.sum()

29

In [133]:
ar.max()

7

In [134]:
ar.min()

0

In [135]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [136]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [137]:
type(np.where(ar>5))

tuple

In [138]:
np.count_nonzero(ar)

8

In [139]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [140]:
ar[1,2] = 0

In [141]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

In [142]:
import sys

In [149]:
py_ar = [0,4,55,2]

In [150]:
np_ar = np.array(py_ar)

In [151]:
sys.getsizeof(1) * len(py_ar)

112

In [152]:
np_ar.itemsize * np_ar.size

16